### ISSUE TITLE
provider name collisions with multiple apps

### ISSUE THREAD

**Issue by Raerten** [moberwasserlechner/capacitor-filesharer#17]
```
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name com.byteowls.capacitor.filesharer.fileprovider (in package com.example.app) is already used by com.example.app.dev]
```
maybe this fork has resolved this issue, can it be merged? https://github.com/jpxd/capacitor-filesharer/commit/87c3c4843f8bca98f257ca73038a7578bade321d

**Comment by moberwasserlechner** [comment]
Sure. 

As providers are a Android thing I guess there is no problem on iOS.

**Comment by Raerten** [comment]
I'v checked on my app and it works

**Comment by moberwasserlechner** [comment]
Sry for the delay. I released a new version a few moments ago.
