### ISSUE TITLE
Can we share a file directly and not as a base64Data  ??

### ISSUE THREAD

**Issue by pratiksan45** [moberwasserlechner/capacitor-filesharer#24]
I have blob zip file, which I want to share ,  but I don't know how to convert the blob file into a base64 data.
is it possible in Filesharer to send files directly and not as a base 64 Data. ???

**Comment by moberwasserlechner** [comment]
Hi,

no that is not possible.

BR, Michael

**Comment by moberwasserlechner** [comment]
I'm converting my downloadable file on the backend. 

In Java 11 you can use that. In other langauges there is for sure something similar.

```
Base64.encodeBase64String(byteArray )
```
