### ISSUE TITLE
Feat: Filesharer@next for Capacitor 3.0.0

### ISSUE THREAD

**Issue by jjlmoya** [moberwasserlechner/capacitor-filesharer#28]
### Describe the Feature
Create a next version for use it in next Capacitor 3.0.0

### Platform(s) Support Requested
- Android
- iOS
- Electron
- Web

![image](https://user-images.githubusercontent.com/29946421/115139862-ae6c2a80-a034-11eb-80ff-4c0533550c9a.png)

### Documentation:

https://capacitorjs.com/docs/v3/updating/plugins/3-0

**Comment by Maheshbhusanoor** [comment]
When it will be available for 3.0?

**Comment by moberwasserlechner** [comment]
I can't give a timeline for this. Maybe end of may, depending of course if I have the time.

**Comment by jjlmoya** [comment]
Thanks @moberwasserlechner, don't worry about it. Happy to read a good answer.

**Comment by moberwasserlechner** [comment]
I successfully tested the 3.0.0 release on

* Android 11
* iOS 12.3.1
* iOS 14.7.1

On iOS i shared to WhatsApp, Mail, File save. It worked every time. No crashes so far.

I'm releasing the new version today.
