### ISSUE TITLE
Feat: Can you share a text, json or csv file?

### ISSUE THREAD

**Issue by ClintonThurman** [moberwasserlechner/capacitor-filesharer#35]
### Describe the Feature
I'd like to be able to share a text, csv and/or json file, but that currently doesn't look possible.

### Platform(s) Support Requested

- Android
- iOS

### Describe Preferred Solution
The ability to also share text, csv and/or json files.

### Describe Alternatives
Since I'm already using your plugin to share images, I'd prefer to use it to share/export text files as well. I know there are ways to get this done with similar plugins, but I'd rather use yours.

### Related Code
        FileSharer.share({
            filename: 'filename.txt',
            base64Data: 'file content',
            contentType: 'text',
        });

### Additional Context
I'm currently using capacitor 2

**Comment by moberwasserlechner** [comment]
No text is not supported. Duplicates #23
