### ISSUE TITLE
No data received with Capacitor Plugin PushNotifications 

### ISSUE THREAD

**Issue by tayfun14** [moberwasserlechner/capacitor-filesharer#4]
Hello @moberwasserlechner ,

I have a bug with [PushNotifications](https://capacitor.ionicframework.com/docs/apis/push-notifications) on Android, when I receive a notification, the app detect it and go inside of the listener, but it's empty (data field is empty).
The problem appears when capacitor-filesharer is installed (just installed with npm, not used).
If I remove "@byteowls/capacitor-filesharer": "^1.0.0-beta.1" from package.json, it fixes the bug.

**Comment by moberwasserlechner** [comment]
Boah, it is difficult to say whats the issue. Could plz answer these question to I get a better idea whats going on.

* Just to be clear, you did not add the Android part of the plugin to `com.companyname.appname.MainActivity#onCreate`
* Do you have any logs?

**Comment by tayfun14** [comment]
Many thanks for your quick answer :)

First, I have to notice you that I'm not an English speaker, so forgive me for my poor grammar. ^^'

About my problem : 

- Initially, I've added the file-sharer plugin in the onCreate method, and used it. It worked fine for what it supposed to do. Unfortunately I noticed after one or two weeks that there was a bug with the received notification listener of Capacitor Push Notifications plugin. Nothing said that the problem came from file-sharer plugin, so it was really difficult to determinate what provoked the bug.

- Unfortunately for both of us, there was not any logs, it's the reason why it was so difficult to find the bug's source.

I created a sample project for you : [sample-file-sharer](https://github.com/tayfun14/sample-file-sharer)
What I did was : 
- ionic start sample-file-sharer blank --capacitor
- npx cap init (with package com.filesharer.sample)
- add PushNotification functionnality in home.page.ts
- add npm @byteowls/capacitor-filesharer
- build/add android
- npx cap sync
- add app com.filesharer.sample in firebase console and downloaded google-service.json
- add google-service.json in android/app 

after these manipulations, I tested push notifications (with firebase console/cloud-messaging), and here are results : 
with file-sharer : 
![console log with file-sharer](https://user-images.githubusercontent.com/17989186/55228682-13207680-521b-11e9-813e-3be9daa3dfcd.JPG)
without file-sharer :
![console log without file-sharer](https://user-images.githubusercontent.com/17989186/55228683-13b90d00-521b-11e9-8e71-c2ad7bfe7807.JPG)

to test with/without, just remove the line "@byteowls/capacitor-filesharer": "^1.0.0-beta.1", and then ionic build/npx cap sync

I removed google-service.json file from android directory (there is some confidential data in it), so you have to create a project/add an app in firebase console to try it. 
Make sure to add your app with the package name "com.filesharer.sample".

**Comment by moberwasserlechner** [comment]
I tested v1.0.1 with Push Notifications from Capacitor 2.0.0-beta.1 and v.2.0.0 (not released yet) with Capacitor 2.0.0 and had no issues.

But it's a year later and thing have improved on both sides. Maybe #17 was one of the reason for this issue.
