### ISSUE TITLE
 File sharing failed: The string contains invalid characters.

### ISSUE THREAD

**Issue by renege** [moberwasserlechner/capacitor-filesharer#5]
Hi,
I'm trying the following code on iOS:
```
sharePhoto() {
     var self = this;
            var img = document.getElementById('photo').attr('src');
            FileSharer.share({
                filename: Math.random()+"_pic.png",
                base64Data: img.replace('data:image/png;base64', '').replace('image/png;base64', ''),
                contentType: "image/png",
            }).then(() => {
                alert('DONE');
            }).catch(error => {
                console.error("File sharing failed:", error.message);
            });
},
```
I'm 100% the picture is correct, because it's shown correctly on the image src. 

But it always gives me: ```⚡️  [error] - File sharing failed: The string contains invalid characters.```

And when I do:
```base64Data: img.replace('data:image/png;base64', '').replace('image/png;base64', '').replace(/\s/g, ''), ```
It gives me: ```ERR_PARAM_DATA_INVALID```

**Comment by renege** [comment]
@moberwasserlechner my ionic app is build in vue with capacitor by the way

**Comment by renege** [comment]
@moberwasserlechner event this fails:
```
    Plugins.FileSharer.share({
                filename: Math.random()+"_foo.png",
                base64Data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAEBgIApD5fRAAAAABJRU5ErkJggg==',
                contentType: "image/png",
            }).then(() => {
                alert('DONE');
            }).catch(error => {
                console.error("File sharing failed:", error.message);
            });
```

**Comment by moberwasserlechner** [comment]
Hi, 

Which versions of capacitor and ios are you using?
Does it work on the Web and Android?

I try to have a look but can not make any promises.

BR, Michael

**Comment by moberwasserlechner** [comment]
Dataurls normally look like `data:image/png;base64,`. See the comma at the end. 

In your code above you do not replace the comma, which might cause the error?

**Comment by renege** [comment]
Thanks, was the comma!

**Comment by loburets** [comment]
Just to emphasise for other users: you don't need the `data:image/png;base64,` part in the base64Data parameter. So, use something like 
`.replace(/^data:image\/[a-z]+;base64,/, "")`

**Comment by pratiksan45** [comment]
Or , If someone want the easiest way you can just    `base64Data: img.split(',')[1],`

**Comment by Maheshbhusanoor** [comment]
FileSharer.share({
                filename: Math.random()+"_foo.png",
                base64Data: 'base64 string here',
                contentType: "image/png",
            }).then(() => {
                alert('DONE');
            }).catch(error => {
                console.error("File sharing failed:", error.message);
            });
            
           Its showing the alert Done but nothing is happening. Can anyone help me with this?

**Comment by jake-nz** [comment]
@Maheshbhusanoor Probably because Capacitor 3 is not supported :(  https://github.com/moberwasserlechner/capacitor-filesharer/issues/31#issuecomment-907005914

**Comment by pareshgami** [comment]
Hello,

Base64 of PDF file is working fine with android but getting error into iOS.

File sharing failed – "ERR_PARAM_DATA_INVALID"

**Comment by JacquesBeets** [comment]
Hey guys, confirming this issue is still happening on Capacitor 4.0.0

**Comment by Jellybing** [comment]
I use this plugin on Capacitor 4.0.0,the app will be closed when share image to wechat or other im,how to solve this problem,thanks.

**Comment by moberwasserlechner** [comment]
Please do not comment on **closed** issues but create a new one and provide the information the issue template asks. I will not look on closed issues when planing a new release and therefore you will not get any answers to your questions.
